version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres:17.6-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=boilerplate_db
  app:
    container_name: python-web-service-boilerplate
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "alembic upgrade head && fastapi run src/python_web_service_boilerplate/__main__.py --port 80"
    ports:
      - "8001:80"
    depends_on:
      - db
    restart: always
    volumes:
      - ~/docker-file-mapping/python-web-service-boilerplate:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      - OFFLINE_ENV=false
      - LOG_LEVEL=INFO
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=boilerplate_db
      - SQL_LOG_ENABLED=false
