name: "Init Project on Windows"
on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'release/**'
      - 'hotfix/**'

jobs:
  build:
    name: "Init New Project on Windows"
    runs-on: windows-2025
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Run Init Script
        shell: powershell
        run: powershell -File .\init_project.ps1 -ProjectName "my_new_awesome_project"
