name: Publish docker image

on:
  push:
    tags: ["*"]
    branches:
      - "release/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Publish to GitHub Packages
      uses: whoan/docker-build-with-cache-action@v8
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        image_name: ${{ github.repository }}
        push_git_tag: true
